view:
  title: PowerTools! for MooTools
  theme: cpojer

packager:
  exports: powertools-1.2.0.js
  contenttype: application/javascript
  charset: UTF-8
  blocks:
  compressors:

packages:
  - "../MooTools/custom-event/"
  - "../MooTools/mobile/"
  - "../MooTools/class-extras/"
  - "../MooTools/history/"
  - "../MooTools/router/"
  - "../MooTools/dynamic-matcher/"
  - "../MooTools/mootilities/"
  - "../MooTools/form-autogrow/"
  - "../MooTools/form-placeholder/"
  - "../MooTools/event-stack/"
  - "../MooTools/tree/"
  - "../MooTools/scroll-loader/"
  - "../MooTools/interface/"
